### ISSUE TITLE
Could this be used in a BCN-based coin?

### ISSUE THREAD

**Issue by zhmrab** [fireice-uk/cryptonote-speedup-demo#1]
title says it all !

**Comment by JollyMort** [comment]
Yes, any CN coin

**Comment by zhmrab** [comment]
Very interesting, how can this be implemented ? Id very much like to test it!

**Comment by fireice-uk** [comment]
You would need to talk to me about licencing the code first.

**Comment by zhmrab** [comment]
@fireice-uk would like to test it and will def would like to talk about licensing it, just finished compiling in ubuntu

:~/cryptonote-speedup-demo/build# ./cn64_show
Generating random test data.
Testing 32 bit code.
^[OQ

32-bit code 17017.7 ms
Testing 64 bit code.
64-bit code 7951.37 ms
Verifying test data.
Verification OK!

**Comment by zhmrab** [comment]
@fireice-uk once library is compiled how do I test it out on a BCN clone?

**Comment by saiaman** [comment]
Any speedup for xmr-stak ?

**Comment by fireice-uk** [comment]
@saiaman no, this is something totally different.

**Comment by e9r8we90r8** [comment]
@fireice-uk , @saiaman just a wallet sync speed up right? this is good for monerujo then?
